using System.Text;

using Microsoft.CodeAnalysis;

namespace Zinq.Contexts.Generators.Emitters;

public class ContextBuilderExtensionEmitter : IContextSourceEmitter
{
    public void Emit(SourceProductionContext context, ContextBuilderInvoke invoke)
    {
        var with = invoke.Type.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var name = $"Dyn_{invoke.SafeName}";
        var source = new StringBuilder();
        var next = invoke.Type.TypeArguments.Count() != 1
            ? null
            : (INamedTypeSymbol)invoke.Type.TypeArguments[0];

        source.AppendLine("// <auto-generated/>");
        source.AppendLine();
        source.AppendLine($"using {invoke.Type.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)};");
        source.AppendIf(next is not null, $"using {next?.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)};");

        source.AppendLine();
        source.AppendLine("namespace Zinq.Contexts.Extensions");
        source.AppendLine("{");
        source.AppendLine("    public static partial class ContextExtensions");
        source.AppendLine("    {");
        source.AppendLine($"        public static {invoke.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)} With{with}(this {next?.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)} context)");
        source.AppendLine("        {");
        source.AppendLine($"            return new {name}(context); // will fill in later");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        context.AddSource($"{name}_Build.g.cs", source.ToString());
    }
}