using System.Text;

using Microsoft.CodeAnalysis;

namespace Zinq.Contexts.Generators.Emitters;

public class ContextClassEmitter : IContextSourceEmitter
{
    public void Emit(SourceProductionContext context, ContextBuilderInvoke invoke)
    {
        var name = $"Dyn_{invoke.SafeName}";
        var source = new StringBuilder();
        var members = invoke.Type.GetMembers()
            .Where(m => m.Kind == SymbolKind.Property && m is IPropertySymbol)
            .Select(m => (IPropertySymbol)m)
            .Select(p =>
            {
                var paramName = p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var typeName = p.GetMethod?.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var src = new StringBuilder()
                    .AppendLine($"public {typeName} {paramName}")
                    .AppendLine("\t\t{");

                if (p.GetMethod is not null)
                {
                    src = src.AppendLine($"\t\t\tget => Get(Key.{p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)});");
                }

                if (p.SetMethod is not null)
                {
                    src = src.AppendLine($"\t\t\tset => Set(Key.{p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}, value);");
                }

                return src.Append("\t\t}").ToString();
            });

        var next = invoke.Type.TypeArguments.Count() != 1
            ? null
            : (INamedTypeSymbol)invoke.Type.TypeArguments[0];

        var nextMembers = next?.GetMembers()
            .Where(m => m.Kind == SymbolKind.Property && m is IPropertySymbol)
            .Select(m => (IPropertySymbol)m)
            .Select(p =>
            {
                var paramName = p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var typeName = p.GetMethod?.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var src = new StringBuilder()
                    .AppendLine($"public {typeName} {paramName}")
                    .AppendLine("\t\t{");

                if (p.GetMethod is not null)
                {
                    src = src.AppendLine($"\t\t\tget => Get(Key.{p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)});");
                }

                if (p.SetMethod is not null)
                {
                    src = src.AppendLine($"\t\t\tset => Set(Key.{p.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}, value);");
                }

                return src.Append("\t\t}").ToString();
            });

        var nextTypeName = next?.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var typeName = invoke.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

        var src =
@$"// <auto-generated/>

using {invoke.Type.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)};
{(next is not null ? $"using {next.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)};" : string.Empty)}

namespace Zinq.Contexts.Extensions
{{
    public class {name}({nextTypeName} context) : Zinq.Contexts.Context<{nextTypeName}>(context), {typeName}, {nextTypeName}
}}";

        source.AppendLine("// <auto-generated/>");
        source.AppendLine();
        source.AppendLine($"using {invoke.Type.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)};");

        if (next is not null)
        {
            source.AppendLine($"using {next.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)};");
        }

        source.AppendLine();
        source.AppendLine("namespace Zinq.Contexts.Extensions");
        source.AppendLine("{");
        source.AppendLine($"    public class {name}({nextTypeName} context) : Zinq.Contexts.Context<{nextTypeName}>(context), {typeName}, {nextTypeName}");
        source.AppendLine($"    {{");
        source.AppendLine($"        {string.Join(Environment.NewLine, members)}");

        if (next is not null)
        {
            source.AppendLine()
                .AppendLine($"\t\t{string.Join(Environment.NewLine, nextMembers)}");
        }

        source.AppendLine($"    }}");
        source.AppendLine("}");
        context.AddSource($"{name}.g.cs", source.ToString());
    }
}