using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using Zinq.Analyze;

namespace Zinq.Contexts.Generators.Components;

public class ContextComponent : IInterfaceComponent
{
    public bool Select(InterfaceDeclarationSyntax syntax) => syntax.AttributeLists.Any();
    public ISource Build(INamedTypeSymbol symbol)
    {
        var next = symbol.TypeArguments.Count() != 1
            ? null
            : symbol.TypeArguments[0];

        return new Source()
        {
            Name = $"Dyn_{symbol.ToIdentifier()}",
            Content = $$"""
            // <auto-generated/>

            namespace Zinq.Contexts.Extensions;

            public class Dyn_{{symbol.ToIdentifier()}}({{next?.FullName ?? "IContext"}} context) : Zinq.Contexts.Context<{{next?.FullName ?? "IContext"}}>(context), {{symbol.FullName}}, {{next?.FullName ?? "IContext"}}
            {
                {{
                    symbol.GetMembers()
                        .Where(m => m.Kind == SymbolKind.Property && m is IPropertySymbol)
                        .Select(m => (IPropertySymbol)m)
                        .Select(p => new ContextPropertyComponent().Build(p))
                        .Render("\t")
                }}{{
                    next?.GetMembers()
                        .Where(m => m.Kind == SymbolKind.Property && m is IPropertySymbol)
                        .Select(m => (IPropertySymbol)m)
                        .SelectMany(p => new ContextPropertyComponent().Build(p).Content)
                        .Render("\t")
                }}
            }

            // public class Dyn_{{symbol.ToIdentifier()}}_Builder<TContext>(IContextBuilder<{}> builder) : IContextBuilder<ILoggerContext<TContext>> where TContext : IContext
            // {
            //     public IContextBuilder<ILoggerContext<TContext>> With(string key, IResolver resolver)
            //     {
            //         builder = builder.With(key, resolver);
            //         return this;
            //     }

            //     public ILoggerContext<TContext> Build()
            //     {
            //         var context = builder.Build();
            //         return new LoggerContext<TContext>(context);
            //     }
            // }

            // public static partial class ContextBuilderExtensions
            // {
            //     public static {{symbol.FullName}} WithLogger()
            // }
            """.Split('\n')
        };
    }
}